[package]
name = "rust-audary"
version = "0.1.0"
authors = ["Masami_Nakaoka <neti0326@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
